export const REGISTER_WIDGET = "REGISTER_WIDGET";
export const ADD_WIDGET = "ADD_WIDGET";
export const REMOVE_WIDGET = "REMOVE_WIDGET";

export const NT_ROBOT_CONNECTION_CHANGED = "NT_ROBOT_CONNECTION_CHANGED";
export const NT_WEBSOCKET_CONNECTION_CHANGED = "NT_WEBSOCKET_CONNECTION_CHANGED";
export const NT_VALUE_CHANGED = "NT_VALUE_CHANGED";
export const INIT_NETWORKTABLES = "INIT_NETWORKTABLES";
export const CLEAR_NETWORKTABLES = "CLEAR_NETWORKTABLES";

export const SOURCES_CHANGED = "SOURCES_CHANGED";