export const REGISTER_WIDGET = "REGISTER_WIDGET";
export const ADD_WIDGET = "ADD_WIDGET";
export const REMOVE_WIDGET = "REMOVE_WIDGET";
export const INIT_SOURCES = "INIT_SOURCES";
export const CLEAR_SOURCES = "CLEAR_SOURCES";
export const REMOVE_SOURCES = "REMOVE_SOURCES";
export const SOURCES_CHANGED = "SOURCES_CHANGED";